language: php

sudo: false

matrix:
  include:
    - php: 5.4
      env: PROCESS_CODECLIMAE=true
    - php: 5.5
    - php: 5.6
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev

script: ./test/bin/ci.bash summary