<?php
/**
 * Created by PhpStorm.
 * User: sghzal
 * Date: 9/14/15
 * Time: 6:01 PM
 */

namespace UForm\Render;


class TwigLoaderFileSystem extends \Twig_Loader_Filesystem {
    public function normalizeName($name)
    {
        $name .= ".twig";
        return parent::normalizeName($name); // TODO: Change the autogenerated stub
    }
}